### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by gamaanderson** [nguy/artview#129] opened 2016-02-06 19:51 UTC
I have the impression there are several small things that need to be done before release 1.2 and I'm afraid I may forget something so I would like to open this issue for reference.

I also invite people to start looking for error, in the current master or in PR #128.

- [x] issue  #61
- [x] issue #127 
- [x] issue #118 
- [x] issue #124 
- [x] roll version
- [x] tutorials (in special issue #118) (make and add link)
- [x] conda package (make and add instructions) 
- [x] re-build doc
- [x] remove old select region in favor of `SelectRegion_dev`
- [x] pep8
- [x] Update README to use the User Forum email for issues and discussions.

(this list don't reflect execution order)

**Comment by nguy** [comment] 2016-02-09 15:27
+1 for the list!

The one thing I think could wait is the select region stuff. This could be a sub version of 1.2 in my opinion.

**Comment by gamaanderson** [comment] 2016-02-09 22:11
if you mean the SelectRegion_dev, this was kind of a question on you. But I would like to know why; what is missing in the dev version?

**Comment by nguy** [comment] 2016-02-10 19:41
Honestly I haven't looked at it in a while. Let me take a look and get back to you.

**Comment by nguy** [comment] 2016-02-19 20:44
@jjhelmus When we get this further along, could you help us build a conda package?

**Comment by jjhelmus** [comment] 2016-02-22 14:55
I'd be happy to help get a conda package built for ARTView, just ping me when you make or are about to make the release and I can start testing out some recipes.

**Comment by nguy** [comment] 2016-02-22 15:16
Thanks! It should be pretty soon.

**Comment by jjhelmus** [comment] 2016-02-22 15:18
Great, I'm traveling this week so might not be as prompt, but I'll keep an eye out.

**Comment by nguy** [comment] 2016-02-22 15:18
@gamaanderson What do you propose for the select region? I would like to keep the display functionality, but agree that having two separate methods will become problematic.

**Comment by gamaanderson** [comment] 2016-02-22 19:40
what funcionalities of do you like to mantain,  that you cannot do in one way or the other in with the new version? I think they are all there.

**Comment by gamaanderson** [comment] 2016-02-22 19:41
@jjhelmus what would be the install instruction once the conda package is made?

**Comment by jjhelmus** [comment] 2016-02-22 20:17
Run `conda install -c jjhelmus artview`.  The jjhelmus part could be replaced with another conda "channel", that has just need where I've been putting the packages I've built.

**Comment by nguy** [comment] 2016-02-22 23:37
I believe the functionality is there, I meant that I'd like to maintain the setup from the Display as it is for now in terms of easily plotting histogram, bringing up table, applying a mask, etc. The newer select region is more modular probably and therefore in the long run more flexible. I just want to make sure we don't lose functionality for the user.

**Comment by nguy** [comment] 2016-02-22 23:40
This sort of goes back to a way back discussion I had with @scollis about open source radar or meteorology having a channel on conda. Would this be something to explore?

**Comment by scollis** [comment] 2016-02-22 23:45
@jjhelmus is the Guru here.. But yes.. this would be a great idea..


Nick wrote:

**Comment by gamaanderson** [comment] 2016-02-23 07:26
@nguy since the code is already there, I have no problem to let the current SelectRegion accessible through the display. But it will become a part of display and lose its status as a components, therefore not accessible through the artview module or any mode.

**Comment by nguy** [comment] 2016-02-23 15:48
I know it's a balance, but I feel that this is a tool for quick data querying. Let's keep it for the time being, with the thought of any other tools developed should use the newer version. Do you think it wise to rename the code to indicate that it is display-based and not a component?

For example, we could rename the class from ```SelectRegion``` to ```DisplaySelectRegion``` or something and have display prominent in all naming. We could then also rename ```SelectRegion_dev``` to ```SelectRegion```.

**Comment by gamaanderson** [comment] 2016-02-23 22:14
ok, I will rename it.

**Comment by nguy** [comment] 2016-02-23 23:08
Thanks @gamaanderson. Could you also replace the the contact in the README file to the user forum email?

**Comment by nguy** [comment] 2016-02-24 23:23
We can probably close some of the outstanding Issues that have been addressed as well. Let me know if you want me to do any of this.

**Comment by nguy** [comment] 2016-02-26 15:26
Okay, it appears that rebuilding docs and rolling version are the two parts that are left. I'll do that today and submit a PR.

At this point we should probably then build the conda package and go forward with the release. If we manage to get this sorted, it would be fun to release on Monday since it's a leap year!

**Comment by nguy** [comment] 2016-02-26 16:31
Ended up pushing the new docs and rolling the rev directly into the master.

@jjhelmus Can we get started with the conda release if you have time?

**Comment by gamaanderson** [comment] 2016-02-26 20:20
Do you think we should do a "what new" in relation to the latest release? It is so much, that I have my doubts if it makes sense.

**Comment by nguy** [comment] 2016-02-26 21:02
I think that's a great idea. We could put this in the README maybe. Then I was going to post that What's New and announcement in the Users forum and the pyaos mailing list.

**Comment by gamaanderson** [comment] 2016-02-26 22:28
The README is already too long!

**Comment by nguy** [comment] 2016-02-26 22:49
Ha, that is true! We should probably move some of this to the Documentation.

**Comment by jjhelmus** [comment] 2016-02-29 20:02
@nguy I'll start working on the artview conda build this week.  I'll keep you all updated if I run into any question.

**Comment by nguy** [comment] 2016-02-29 21:23
Thanks!

**Comment by nguy** [comment] 2016-03-01 16:54
@jjhelmus I just pushed a minor update. I don't think this affects the conda build, but just in case....

**Comment by gamaanderson** [comment] 2016-03-02 10:41
yes, it does afect. If the conda package is build from the old code then the tool would continue broken.

**Comment by jjhelmus** [comment] 2016-03-02 18:48
I created test artview conda packages from the ae1331f56 commit which I labeled as "1.2.3".  These are available on my [Anaconda.org channel](https://anaconda.org/jjhelmus/artview) with the label "testing".  

If you use `git tag` to [tag a release](https://git-scm.com/book/en/v2/Git-Basics-Tagging) it will be easier to create the conda package for 1.2.  Just let me know the tag/commit that should be considered 1.2 for the conda package and I can update the package quickly.

**Comment by gamaanderson** [comment] 2016-03-02 19:40
Thank you a lot @jjhelmus 

@nguy PR #132 can be merged. I would also like to call attention to the `ISRELEASED` flag in **setup.py** line 57, in case you haven't already seen it.

**Comment by nguy** [comment] 2016-03-02 19:58
I want to make sure I follow what to do here. 

1. I can merge #132 (with the ISRELEASED flag turned on - thanks @gamaanderson I did not see this.)
2. Apply the tag to it with something like conda release as description. 
3. Do I need to do a formal release via Github also?
4. After all of this the "real" artview conda package will be released.

**Comment by nguy** [comment] 2016-03-02 20:04
Or do I need to just do step 2 and the rest can come afterward. Sorry, try to figure out the workflow here.

**Comment by jjhelmus** [comment] 2016-03-02 20:45
You can do steps 3 and 4 anytime after after you change ISRELEASED to True and tag the release, there is no immediacy.  Setting ISRELEASE to True indicates that commit corresponds to the "official" release version and tagging makes it easier to find rather than having to use the commit hash.  It is good to make a second commit immediately after to flip ISRELEASED back to False and roll the version number.  

Examples from the last release of Py-ART:

* [REL Release 1.6.0](https://github.com/ARM-DOE/pyart/commit/7876d8733d43818e752e009ef51e3e569f331501)
* [MAINT: start v1.7+dev](https://github.com/ARM-DOE/pyart/commit/c54a29916defa36b8f16ef849c8c1c35a7d755dd)

There are other workflows that projects use for this process that involves release branches, etc, but I've never found that necessary.

**Comment by nguy** [comment] 2016-03-02 21:10
Thanks @jjhelmus for walking us through this!

Okay the tag is done.

**Comment by nguy** [comment] 2016-03-02 21:19
The method for Py-ART seems to be a good one to follow. @gamaanderson any thoughts?
This would give us a benchmark for development.

**Comment by jjhelmus** [comment] 2016-03-02 21:20
FYI, `git push` doesn't push tags by default, you need to use `git push --tags`.

**Comment by nguy** [comment] 2016-03-02 21:22
done, thanks

**Comment by nguy** [comment] 2016-03-02 21:24
FYI, this will close Issue #105 I believe.

Also, @jjhelmus would you be willing to help with future conda releases? If so, we should ping you when appropriate?

**Comment by jjhelmus** [comment] 2016-03-02 21:27
Happy to.  I'll set up the system for building the conda package on [conda-forge](https://conda-forge.github.io/) so that anyone can make a release by submitting a pull request.

**Comment by nguy** [comment] 2016-03-02 21:28
Great! You'll probably need to lead me through that as well eventually.

**Comment by nguy** [comment] 2016-03-02 21:29
We should sit and chat at SEA conference to discuss parallel developments.

**Comment by jjhelmus** [comment] 2016-03-02 21:33
Sounds like a plan.

**Comment by gamaanderson** [comment] 2016-03-02 21:36
I have always been in favor of following pyart example when applicable.

**Comment by nguy** [comment] 2016-03-02 22:02
Me too, let @jjhelmus do the hard work. ;p

**Comment by nguy** [comment] 2016-03-02 22:04
Okay back on topic, do we need anything else for the conda package then?

**Comment by jjhelmus** [comment] 2016-03-02 22:05
A full suite of conda packages for artview 1.2 made and available on [Anaconda.org](https://anaconda.org/jjhelmus/artview/files).  I need to fix a few items on conda-forge before moving the build there.

**Comment by nguy** [comment] 2016-03-02 22:34
Excellent, thank you again and let us know anything else we can do to help.

**Comment by jjhelmus** [comment] 2016-03-07 15:29
I created a [conda-forge feedstock for artview](https://github.com/conda-forge/artview-feedstock/) which allows for reproducible builds of the conda package using online CI services.  Anyone can submit a pull request that repository when updates are needed.  The command to install the packages produced by this setup is `conda install -c https://conda.anaconda.org/conda-forge artview`.  I prefer this more open method for building but will continue to maintain the packages on my personal anaconda.org channel, jjhelmus.

**Comment by nguy** [comment] 2016-03-08 22:00
The official V1.2 release is in the wild!

**Comment by nguy** [comment] 2016-03-09 16:23
Realized I forgot to do the ISRELEASED. So pushed this as REL commit and updated the Release tag.
Then pushed a v1.3dev commit afterwards.

**Comment by gamaanderson** [comment] 2016-03-10 22:48
Can this be closed?

**Comment by nguy** [comment] 2016-03-10 23:09
Yep

**Closed** 2016-03-10 23:36 UTC
